name: wics_hackathon_2026
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^6.2.0
  cloud_firestore: ^6.1.3
  firebase_core: ^4.5.0
  image_picker: ^1.0.7

  fl_chart: ^0.68.0
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/gympost.avif
    - assets/images/guitar.jpg
    - assets/images/chess.avif
    - assets/images/painting.webp
    - lib/images/boxing.jpg
    - lib/images/gaming.jpg
    - lib/images/gym.jpg
    - lib/images/picketball.jpg
    - lib/images/soccer.jpg
    - lib/images/tennis.png
    - lib/images/gamescene1.jpg
    - lib/images/gamescene2.jpg
